# This is a basic workflow to help you get started with Actions

name: TrinityCore335编译

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: 准备环境
        run: |
          sudo apt-get update
          sudo apt-get install -y git clang cmake make gcc g++ libmariadbclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev p7zip libmariadb-client-lgpl-dev-compat
          sudo apt install -y mariadb-server-10.3
          sudo apt-get install -y mariadb-server
      - name: 开始克隆源码
        #env:
          # 你希望服务端放在你电脑的什么位置。我这里是/mnt/sdb
          # Work_folder: /mnt/sdb
        run: |
          git clone  -b 3.3.5 git://github.com/TrinityCore/TrinityCore.git
      - name: 开始编译
        run: |
          mkdir server335
          cd TrinityCore
          # 单人秒排副本
          sed -i "s/numPlayers\ \=\ 0\;/numPlayers\ \=\ 4\;/g" ./src/server/game/DungeonFinding/LFGQueue.cpp
          mkdir build
          cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=../../server335
          make -j $(nproc) install
          mv ../sql ../../server335
          # sed -i "s/SourceDirectory\ \ \=\ \"\"/SourceDirectory\ \ \=\ \"..\/sql\"/g" ../../server335/etc/worldserver.conf.dist
      - name: 上传固件
        uses: actions/upload-artifact@master
        if: success()
        with:
          name: TrinityCore335_linux_server
          path: ./server335
